# .nixpacks.toml

# Define the phases for installing dependencies and building the application
[phases]
  # Phase for installing backend dependencies
  [phases.install]
    commands = [
      "pip install -r backend/requirements.txt"  # Install Python dependencies for the backend
    ]
  
  # Phase for building the React frontend application
  [phases.build]
    commands = [
      "cd my-react-app && npm install && npm run build"  # Install Node.js dependencies and build the frontend
    ]

# Define the start command to run your backend server
[start]
  command = "gunicorn backend.main:app"  # Adjust the module path as needed

# Define static files to serve
[static]
path = "my-react-app/build"  # Path to the built React app, change to `dist` if that's the output folder name
