# Example .nixpacks.toml

# Define phases for installing dependencies and building the application
[phases]
  # Install backend dependencies
  [phases.install]
    commands = [
      "pip install -r backend/requirements.txt"  # Install Python backend dependencies
    ]
  
  # Build the React frontend application
  [phases.build]
    commands = [
      "cd my-react-app && npm install && npm run build"  # Install Node.js dependencies and build frontend
    ]

# Specify the start command for the backend
[start]
  command = "gunicorn backend.main:app"  # Adjust if necessary

# If serving static files from the frontend build output
[static]
path = "my-react-app/dist"  # Directory where the build files are located
