[phases.setup]
commands = [
  "pip install --upgrade pip setuptools wheel"
]

[phases.build]
commands = [
  "pip install -r backend/requirements.txt"
]

[phases.start]
commands = [
  "gunicorn backend.main:app"
]
